<?php
/**
 * Numerno - Euro.message Magento Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the NUMERNO EUROMESSAGE MAGENTO EXTENSION License, which extends the Open Software
 * License (OSL 3.0). The Euro.message Magento Extension License is available at this URL:
 * http://numerno.com/licenses/euromsg-ce.txt The Open Software License is available at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * By adding to, editing, or in any way modifying this code, Numerno is not held liable for any inconsistencies or
 * abnormalities in the behaviour of this code. By adding to, editing, or in any way modifying this code, the Licensee
 * terminates any agreement of support offered by Numerno, outlined in the provided Euro.message Magento Extension
 * License.
 * Upon discovery of modified code in the process of support, the Licensee is still held accountable for any and all
 * billable time Numerno spent during the support process. Numerno does not guarantee compatibility with any other
 * Magento extension. Numerno is not responsbile for any inconsistencies or abnormalities in the behaviour of this
 * code if caused by other Magento extension.
 * If you did not receive a copy of the license, please send an email to info@numerno.com or call +90-212-223-5093,
 * so we can send you a copy immediately.
 *
 * @category   [Numerno]
 * @package    [Numerno_Euromsg]
 * @copyright  Copyright (c) 2015 Numerno Bilisim Hiz. Tic. Ltd. Sti. (http://numerno.com/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Order History Block
 *
 * @category   Numerno
 * @package    Numerno_Euromsg
 * @author     Numerno Bilisim Hiz. Tic. Ltd. Sti. <info@numerno.com>
 */
?>
<?php /* @var $this Numerno_Euromsg_Block_Adminhtml_Sales_Order_View_History */ ?>

<div id="order_history_block">
    <?php if ($this->canAddComment()):?>
        <div id="history_form" class="order-history-form">
            <div><?php echo Mage::helper('sales')->__('Add Order Comments') ?></div>
        <span class="field-row">
            <label class="normal" for="history_status"><?php echo Mage::helper('sales')->__('Status') ?></label><br/>
            <select name="history[status]" class="select" id="history_status">
                <?php foreach ($this->getStatuses() as $_code=>$_label): ?>
                    <option value="<?php echo $_code ?>"<?php if($_code==$this->getOrder()->getStatus()): ?> selected="selected"<?php endif; ?>><?php echo $_label ?></option>
                <?php endforeach; ?>
            </select>
        </span>
        <span class="field-row">
            <label class="normal" for="history_comment"><?php echo Mage::helper('sales')->__('Comment') ?></label>
            <textarea name="history[comment]" rows="3" cols="5" style="height:6em; width:99%;" id="history_comment"></textarea>
        </span>
            <div class="f-left">
                <?php if ($this->canSendCommentEmail()): ?>
                    <input name="history[is_customer_notified]" type="checkbox" id="history_notify" value="1" /><label class="normal" for="history_notify"> <?php echo Mage::helper('sales')->__('Notify Customer by Email') ?></label><br />
                <?php endif; ?>
                <?php if ($this->canSendCommentSms()): ?>
                    <input name="history[is_customer_notified_by_sms]" type="checkbox" id="history_notify_by_sms" value="1" /><label class="normal" for="history_notify_by_sms"> <?php echo Mage::helper('euromsg')->__('Notify Customer by SMS') ?></label><br />
                <?php endif; ?>
                <input name="history[is_visible_on_front]" type="checkbox" id="history_visible" value="1" /><label class="normal" for="history_visible"> <?php echo Mage::helper('sales')->__('Visible on Frontend') ?></label>
            </div>
            <div class="f-right">
                <?php echo $this->getChildHtml('submit_button') ?>
            </div>
            <div class="clear"></div>
        </div>
        <div class="divider"></div>
    <?php endif;?>
    <ul class="note-list">
        <?php foreach ($this->getOrder()->getStatusHistoryCollection(true) as $_item): ?>
            <li>
                <strong><?php echo $this->helper('core')->formatDate($_item->getCreatedAtDate(), 'medium') ?></strong>
                <?php echo $this->helper('core')->formatTime($_item->getCreatedAtDate(), 'medium') ?><span class="separator">|</span><strong><?php echo $_item->getStatusLabel() ?></strong><br/><small><?php echo $this->helper('sales')->__('Customer') ?>
                    <strong class="subdue">
                        <?php if ($this->isCustomerNotificationNotApplicable($_item)): ?>
                            <?php echo $this->helper('sales')->__('Notification Not Applicable') ?>
                        <?php elseif ($_item->getIsCustomerNotified()): ?>
                            <?php echo $this->helper('sales')->__('Notified') ?>
                            <img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16" height="16" alt="" />
                        <?php else: ?>
                            <?php echo $this->helper('sales')->__('Not Notified') ?>
                        <?php endif; ?>
                    </strong></small>
                <?php if ($_item->getComment()): ?>
                    <br/><?php echo $this->escapeHtml($_item->getComment(), array('b', 'br', 'strong', 'i', 'u', 'a')) ?>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
    <script type="text/javascript">
        if($('order_status'))$('order_status').update('<?php echo $this->getOrder()->getStatusLabel() ?>');
    </script>
</div>
