<?php
/**
 * Numerno - Euro.message Magento Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the NUMERNO EUROMESSAGE MAGENTO EXTENSION License, which extends the Open Software
 * License (OSL 3.0). The Euro.message Magento Extension License is available at this URL:
 * http://numerno.com/licenses/euromsg-ce.txt The Open Software License is available at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * By adding to, editing, or in any way modifying this code, Numerno is not held liable for any inconsistencies or
 * abnormalities in the behaviour of this code. By adding to, editing, or in any way modifying this code, the Licensee
 * terminates any agreement of support offered by Numerno, outlined in the provided Euro.message Magento Extension
 * License.
 * Upon discovery of modified code in the process of support, the Licensee is still held accountable for any and all
 * billable time Numerno spent during the support process. Numerno does not guarantee compatibility with any other
 * Magento extension. Numerno is not responsbile for any inconsistencies or abnormalities in the behaviour of this
 * code if caused by other Magento extension.
 * If you did not receive a copy of the license, please send an email to info@numerno.com or call +90-212-223-5093,
 * so we can send you a copy immediately.
 *
 * @category   [Numerno]
 * @package    [Numerno_Euromsg]
 * @copyright  Copyright (c) 2015 Numerno Bilisim Hiz. Tic. Ltd. Sti. (http://numerno.com/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Order Comments View Block
 *
 * @category   Numerno
 * @package    Numerno_Euromsg
 * @author     Numerno Bilisim Hiz. Tic. Ltd. Sti. <info@numerno.com>
 */
?>
<?php /* @var $this Numerno_Euromsg_Block_Adminhtml_Sales_Order_Comments_View */ ?>
<?php if ($_entity = $this->getEntity()): ?>
    <div id="comments_block">
    <span class="field-row">
        <label class="normal" for="history_comment"><?php echo Mage::helper('sales')->__('Comment Text') ?></label>
        <textarea name="comment[comment]" rows="3" cols="5" style="height:6em; width:99%;" id="history_comment"></textarea>
    </span>
        <div class="f-left">
            <?php if ($this->canSendCommentEmail()): ?>
                <input name="comment[is_customer_notified]" type="checkbox" id="history_notify" value="1" />
                <label class="normal" for="history_notify"><?php echo Mage::helper('sales')->__('Notify Customer by Email') ?></label><br />
            <?php endif; ?>

            <?php if ($this->canSendCommentSms()): ?>
                <input name="comment[is_customer_notified_by_sms]" type="checkbox" id="history_notify_by_sms" value="1" />
                <label class="normal" for="history_notify_by_sms"><?php echo Mage::helper('euromsg')->__('Notify Customer by SMS') ?></label><br />
            <?php endif; ?>
            <input name="comment[is_visible_on_front]" type="checkbox" id="history_visible" value="1" /><label class="normal" for="history_visible"> <?php echo Mage::helper('sales')->__('Visible on Frontend') ?></label>
        </div>
        <div class="f-right">
            <?php echo $this->getChildHtml('submit_button') ?>
        </div>
        <div class="clear"></div>
        <ul class="note-list">
            <?php foreach ($_entity->getCommentsCollection(true) as $_comment): ?>
                <li>
                    <strong><?php echo $this->helper('core')->formatDate($_comment->getCreatedAtDate(), 'medium') ?></strong>
                    <?php echo $this->helper('core')->formatTime($_comment->getCreatedAtDate(), 'medium') ?><span class="separator">|</span><small><?php echo $this->helper('sales')->__('Customer') ?>
                        <strong class="subdue">
                            <?php if ($_comment->getIsCustomerNotified()): ?>
                                <?php echo $this->helper('sales')->__('Notified') ?>
                                <img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16" height="16" alt="" />
                            <?php else: ?>
                                <?php echo $this->helper('sales')->__('Not Notified') ?>
                            <?php endif; ?>
                        </strong></small>
                    <br/>
                    <?php echo $this->escapeHtml($_comment->getComment(), array('b', 'br', 'strong', 'i', 'u', 'a')) ?>
                </li>
            <?php endforeach; ?>
        </ul>
        <script type="text/javascript">
            function submitComment() {
                submitAndReloadArea($('comments_block').parentNode, '<?php echo $this->getSubmitUrl() ?>')
            }

            if ($('submit_comment_button')) {
                $('submit_comment_button').observe('click', submitComment);
            }
        </script>
    </div>
<?php endif; ?>
